SELECT * FROM sheet1$

/*
INSERT INTO kelompokbarang 
SELECT KDKATEGORI, NAMAKATEGORI, '1', NOW(), '9999999999' FROM sheet1$
	group by KDKATEGORI, NAMAKATEGORI order by KDKATEGORI
*/

/*
INSERT INTO barang
SELECT CONCAT(trim(KDBARANG), '2025'), KDBARANG, NAMABARANG, null, MERK, `TYPE`, SATUAN, '2025', KDKATEGORI, NOW(), NOW(), '9999999999'
	FROM sheet1$
*/